CREATE TABLE WORKPLACE ( 
	C_NAME     	VARCHAR2(255) NOT NULL,
	C_USER_ID	VARCHAR2(255) NOT NULL,
	C_GROUP_ID	VARCHAR2(255) NOT NULL,
	C_SHARE_ID	VARCHAR2(255) NULL,
	C_INDEX  	VARCHAR2(255) NOT NULL,
	C_PARENT_INDEX  	VARCHAR2(255) NULL,
	C_VISUALATTRIBUTES   	CHAR(3) NOT NULL,
	C_PROTECTED_ACCESS    	CHAR(1) NULL,
	C_TOOLTIP      	VARCHAR2(255) NULL,
	C_WORK_XML      	CLOB NULL,
	C_WORK_XML_SCHEMA      	CLOB NULL,
	C_WORK_XML_I2B2_TYPE      	VARCHAR2(255) NULL,
	C_ENTRY_DATE   	DATE NULL,
	C_CHANGE_DATE  	DATE NULL,
	C_STATUS_CD    	CHAR(1) NULL 
	);

	
CREATE TABLE WORKPLACE_ACCESS ( 
	C_TABLE_CD   	VARCHAR2(255) NOT NULL,
	C_TABLE_NAME      VARCHAR2(255) NOT NULL,
	C_PROTECTED_ACCESS    	CHAR(1) NULL,
	C_HLEVEL	INT NOT NULL,
	C_NAME     	VARCHAR2(255) NOT NULL,
	C_USER_ID	VARCHAR2(255) NOT NULL,
	C_GROUP_ID	VARCHAR2(255) NOT NULL,
	C_SHARE_ID	VARCHAR2(255) NULL,
	C_INDEX  	VARCHAR2(255) NOT NULL,
	C_PARENT_INDEX  	VARCHAR2(255) NULL,
	C_VISUALATTRIBUTES   	CHAR(3) NOT NULL,
	C_TOOLTIP      	VARCHAR2(255) NULL,
	C_ENTRY_DATE   	DATE NULL,
	C_CHANGE_DATE  	DATE NULL,
	C_STATUS_CD    	CHAR(1) NULL 
	);
	
CREATE TABLE WORK_DB_LOOKUP ( 
	c_domain_id    	VARCHAR2(255) NOT NULL,
	c_project_path 	VARCHAR2(255) NOT NULL,
	c_owner_id     	VARCHAR2(255) NOT NULL,
	c_db_fullschema	VARCHAR2(255) NOT NULL,
	c_db_datasource	VARCHAR2(255) NOT NULL,
	c_db_servertype	VARCHAR2(255) NOT NULL,
	c_db_nicename  	VARCHAR2(255) NOT NULL,
	c_db_tooltip   	VARCHAR2(255) NULL,
	c_comment      	CLOB NULL,
	c_entry_date   	DATE NULL,
	c_change_date  	DATE NULL,
	c_status_cd    	CHAR(1) NULL 
	)	;


	
	