CREATE TABLE WORKPLACE ( 
	C_NAME     	VARCHAR(255) NOT NULL,
	C_USER_ID	VARCHAR(255) NOT NULL,
	C_GROUP_ID	VARCHAR(255) NOT NULL,
	C_SHARE_ID	VARCHAR(255) NULL,
	C_PROTECTED_ACCESS    	CHAR(1) NULL,
	C_INDEX  	VARCHAR(255) NOT NULL,
	C_PARENT_INDEX  	VARCHAR(255)NULL,
	C_VISUALATTRIBUTES   	CHAR(3) NOT NULL,
	C_TOOLTIP      	VARCHAR(255) NULL,
	C_WORK_XML      	TEXT NULL,
	C_WORK_XML_SCHEMA      	TEXT NULL,
	C_WORK_XML_I2B2_TYPE      	VARCHAR(255) NULL,
	C_ENTRY_DATE   	DATETIME NULL,
	C_CHANGE_DATE  	DATETIME NULL,
	C_STATUS_CD    	CHAR(1) NULL 
	)

	
CREATE TABLE WORKPLACE_ACCESS ( 
	C_TABLE_CD   	VARCHAR(255) NOT NULL,
	C_TABLE_NAME      VARCHAR(255) NOT NULL,
	C_PROTECTED_ACCESS    	CHAR(1) NULL,
	C_HLEVEL	INT	NOT NULL,
	C_NAME     	VARCHAR(255) NOT NULL,
	C_USER_ID	VARCHAR(255) NOT NULL,
	C_GROUP_ID	VARCHAR(255) NOT NULL,
	C_SHARE_ID	VARCHAR(255) NULL,
	C_INDEX  	VARCHAR(255) NOT NULL,
	C_PARENT_INDEX  	VARCHAR(255)NULL,
	C_VISUALATTRIBUTES   	CHAR(3) NOT NULL,
	C_TOOLTIP      	VARCHAR(255) NULL,
	C_ENTRY_DATE   	DATETIME NULL,
	C_CHANGE_DATE  	DATETIME NULL,
	C_STATUS_CD    	CHAR(1) NULL 
	)
	
CREATE TABLE WORK_DB_LOOKUP ( 
	c_domain_id    	VARCHAR(255) NOT NULL,
	c_project_path 	VARCHAR(255) NOT NULL,
	c_owner_id     	VARCHAR(255) NOT NULL,
	c_db_fullschema	VARCHAR(255) NOT NULL,
	c_db_datasource	VARCHAR(255) NOT NULL,
	c_db_servertype	VARCHAR(255) NOT NULL,
	c_db_nicename  	VARCHAR(255) NOT NULL,
	c_db_tooltip   	VARCHAR(255) NULL,
	c_comment      	TEXT NULL,
	c_entry_date   	DATETIME NULL,
	c_change_date  	DATETIME NULL,
	c_status_cd    	CHAR(1) NULL 
	)	


	
	