
ALTER TABLE I2B2METADATA.TABLE_ACCESS RENAME COLUMN "C_PROJECT" TO "C_PROTECTED_ACCESS";

UPDATE I2B2METADATA.TABLE_ACCESS
SET "C_PROTECTED_ACCESS"='N';

ALTER TABLE I2B2METADATA.I2B2 MODIFY ( "C_BASECODE" VARCHAR2(450) );

ALTER TABLE I2B2METADATA.TABLE_ACCESS MODIFY ( "C_PROTECTED_ACCESS" CHAR(1) );

ALTER TABLE I2B2METADATA.TABLE_ACCESS DROP COLUMN "C_ROLE";
	
ALTER TABLE I2B2METADATA.TABLE_ACCESS RENAME COLUMN "C_TABLENAME" TO "C_DIMTABLENAME";

	
	CREATE TABLE I2B2METADATA.ONT_DB_LOOKUP ( 
	c_domain_id    	VARCHAR2(255),
	c_project_path 	VARCHAR2(255),
	c_owner_id     	VARCHAR2(255),
	c_db_fullschema	VARCHAR2(255),
	c_db_datasource	VARCHAR2(255),
	c_db_servertype	VARCHAR2(255),
	c_db_nicename  	VARCHAR2(255),
	c_db_tooltip   	VARCHAR2(255),
	c_comment      	CLOB,
	c_entry_date   	DATE,
	c_change_date  	DATE,
	c_status_cd    	CHAR(1)
	);