package edu.harvard.i2b2.crc.datavo.db;
// Generated Sep 25, 2006 1:09:02 PM by Hibernate Tools 3.1.0.beta5


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * QtQueryStatus generated by hbm2java
 */
public class QtQueryStatus  implements java.io.Serializable {

    // Fields    

     private Integer statusId;
     private QtQueryStatusType qtQueryStatusType;
     private Date dateStarted;
     private Date dateFinished;
     private Set<QtQueryInstance> qtQueryInstances = new HashSet<QtQueryInstance>(0);

     // Constructors

    /** default constructor */
    public QtQueryStatus() {
    }

	/** minimal constructor */
    public QtQueryStatus(Integer statusId, QtQueryStatusType qtQueryStatusType, Date dateStarted) {
        this.statusId = statusId;
        this.qtQueryStatusType = qtQueryStatusType;
        this.dateStarted = dateStarted;
    }
    /** full constructor */
    public QtQueryStatus(Integer statusId, QtQueryStatusType qtQueryStatusType, Date dateStarted, Date dateFinished, Set<QtQueryInstance> qtQueryInstances) {
       this.statusId = statusId;
       this.qtQueryStatusType = qtQueryStatusType;
       this.dateStarted = dateStarted;
       this.dateFinished = dateFinished;
       this.qtQueryInstances = qtQueryInstances;
    }
    
   
    // Property accessors
    public Integer getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }
    public QtQueryStatusType getQtQueryStatusType() {
        return this.qtQueryStatusType;
    }
    
    public void setQtQueryStatusType(QtQueryStatusType qtQueryStatusType) {
        this.qtQueryStatusType = qtQueryStatusType;
    }
    public Date getDateStarted() {
        return this.dateStarted;
    }
    
    public void setDateStarted(Date dateStarted) {
        this.dateStarted = dateStarted;
    }
    public Date getDateFinished() {
        return this.dateFinished;
    }
    
    public void setDateFinished(Date dateFinished) {
        this.dateFinished = dateFinished;
    }
    public Set<QtQueryInstance> getQtQueryInstances() {
        return this.qtQueryInstances;
    }
    
    public void setQtQueryInstances(Set<QtQueryInstance> qtQueryInstances) {
        this.qtQueryInstances = qtQueryInstances;
    }




}


