/*******************************************************************************
 * Copyright (c) 2006-2018 Massachusetts General Hospital 
 * All rights reserved. This program and the accompanying materials 
 * are made available under the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. I2b2 is also distributed under
 * the terms of the Healthcare Disclaimer.
 ******************************************************************************/
package edu.harvard.i2b2.crc.datavo.db;

// Generated Oct 10, 2006 5:52:18 PM by Hibernate Tools 3.1.0.beta5

import java.util.HashSet;
import java.util.Set;

/**
 * QtQueryResultType generated by hbm2java
 */
public class QtQueryResultType implements java.io.Serializable {

	// Fields

	private int resultTypeId;
	private String name;
	private String description;
	private String displayType;
	private String visualAttributeType;
	private String userRoleCd;
	private String classname;

	public String getClassname() {
		return classname;
	}

	public void setClassname(String classname) {
		this.classname = classname;
	}

	private Set<QtQueryResultInstance> qtQueryResultInstances = new HashSet<QtQueryResultInstance>(
			0);

	public final static String PATIENT_COUNT_XML = "PATIENT_COUNT_XML"; 
	// Constructors

	/** default constructor */
	public QtQueryResultType() {
	}

	/** minimal constructor */
	public QtQueryResultType(int resultTypeId) {
		this.resultTypeId = resultTypeId;
	}

	/** full constructor */
	public QtQueryResultType(int resultTypeId, String name, String description, String userRoleCd,
			Set<QtQueryResultInstance> qtQueryResultInstances) {
		this.resultTypeId = resultTypeId;
		this.name = name;
		this.description = description;
		this.userRoleCd = userRoleCd;
		this.qtQueryResultInstances = qtQueryResultInstances;
	}

	public String getUserRoleCd() {
		return userRoleCd;
	}

	public void setUserRoleCd(String userRoleCd) {
		this.userRoleCd = userRoleCd;
	}

	// Property accessors
	public int getResultTypeId() {
		return this.resultTypeId;
	}

	public void setResultTypeId(int resultTypeId) {
		this.resultTypeId = resultTypeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDisplayType() {
		return displayType;
	}

	public void setDisplayType(String displayType) {
		this.displayType = displayType;
	}

	public String getVisualAttributeType() {
		return visualAttributeType;
	}

	public void setVisualAttributeType(String visualAttributeType) {
		this.visualAttributeType = visualAttributeType;
	}

	public Set<QtQueryResultInstance> getQtQueryResultInstances() {
		return this.qtQueryResultInstances;
	}

	public void setQtQueryResultInstances(
			Set<QtQueryResultInstance> qtQueryResultInstances) {
		this.qtQueryResultInstances = qtQueryResultInstances;
	}

}
