package edu.harvard.i2b2.crc.datavo.db;
// Generated Oct 10, 2006 5:52:18 PM by Hibernate Tools 3.1.0.beta5


import java.util.HashSet;
import java.util.Set;

/**
 * QtQueryStatusType generated by hbm2java
 */
public class QtQueryStatusType  implements java.io.Serializable {

    // Fields    

     private int statusTypeId;
     private String name;
     private String description;
     private Set<QtQueryInstance> qtQueryInstances = new HashSet<QtQueryInstance>(0);
     private Set<QtQueryResultInstance> qtQueryResultInstances = new HashSet<QtQueryResultInstance>(0);

     // Constructors

    /** default constructor */
    public QtQueryStatusType() {
    }

	/** minimal constructor */
    public QtQueryStatusType(int statusTypeId) {
        this.statusTypeId = statusTypeId;
    }
    /** full constructor */
    public QtQueryStatusType(int statusTypeId, String name, String description, Set<QtQueryInstance> qtQueryInstances, Set<QtQueryResultInstance> qtQueryResultInstances) {
       this.statusTypeId = statusTypeId;
       this.name = name;
       this.description = description;
       this.qtQueryInstances = qtQueryInstances;
       this.qtQueryResultInstances = qtQueryResultInstances;
    }
    
   
    // Property accessors
    public int getStatusTypeId() {
        return this.statusTypeId;
    }
    
    public void setStatusTypeId(int statusTypeId) {
        this.statusTypeId = statusTypeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<QtQueryInstance> getQtQueryInstances() {
        return this.qtQueryInstances;
    }
    
    public void setQtQueryInstances(Set<QtQueryInstance> qtQueryInstances) {
        this.qtQueryInstances = qtQueryInstances;
    }
    public Set<QtQueryResultInstance> getQtQueryResultInstances() {
        return this.qtQueryResultInstances;
    }
    
    public void setQtQueryResultInstances(Set<QtQueryResultInstance> qtQueryResultInstances) {
        this.qtQueryResultInstances = qtQueryResultInstances;
    }




}


