//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.22 at 10:48:46 AM EDT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.i2b2.org/xsd/cell/crc/pdo/1.1/")
package edu.harvard.i2b2.crc.datavo.pdo.query;
