//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.17 at 02:57:35 PM EDT 
//


package edu.harvard.i2b2.pm.datavo.i2b2versionmessage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for response_messageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="response_messageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="message_header" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="message_body">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="i2b2_message_version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="i2b2_version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="jdk_version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="os_version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="java_memory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="disk_usage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="app_server_version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="axis2_version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "response_messageType", propOrder = {
    "messageHeader",
    "messageBody"
})
public class ResponseMessageType {

    @XmlElement(name = "message_header", required = true)
    protected String messageHeader;
    @XmlElement(name = "message_body", required = true)
    protected ResponseMessageType.MessageBody messageBody;

    /**
     * Gets the value of the messageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageHeader(String value) {
        this.messageHeader = value;
    }

    /**
     * Gets the value of the messageBody property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseMessageType.MessageBody }
     *     
     */
    public ResponseMessageType.MessageBody getMessageBody() {
        return messageBody;
    }

    /**
     * Sets the value of the messageBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseMessageType.MessageBody }
     *     
     */
    public void setMessageBody(ResponseMessageType.MessageBody value) {
        this.messageBody = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="i2b2_message_version" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="i2b2_version" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="jdk_version" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="os_version" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="java_memory" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="disk_usage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="app_server_version" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="axis2_version" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "i2B2MessageVersion",
        "i2B2Version",
        "jdkVersion",
        "osVersion",
        "javaMemory",
        "diskUsage",
        "appServerVersion",
        "axis2Version"
    })
    public static class MessageBody {

        @XmlElement(name = "i2b2_message_version", required = true)
        protected String i2B2MessageVersion;
        @XmlElement(name = "i2b2_version", required = true)
        protected String i2B2Version;
        @XmlElement(name = "jdk_version", required = true)
        protected String jdkVersion;
        @XmlElement(name = "os_version", required = true)
        protected String osVersion;
        @XmlElement(name = "java_memory", required = true)
        protected String javaMemory;
        @XmlElement(name = "disk_usage", required = true)
        protected String diskUsage;
        @XmlElement(name = "app_server_version", required = true)
        protected String appServerVersion;
        @XmlElement(name = "axis2_version", required = true)
        protected String axis2Version;

        /**
         * Gets the value of the i2B2MessageVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getI2B2MessageVersion() {
            return i2B2MessageVersion;
        }

        /**
         * Sets the value of the i2B2MessageVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setI2B2MessageVersion(String value) {
            this.i2B2MessageVersion = value;
        }

        /**
         * Gets the value of the i2B2Version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getI2B2Version() {
            return i2B2Version;
        }

        /**
         * Sets the value of the i2B2Version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setI2B2Version(String value) {
            this.i2B2Version = value;
        }

        /**
         * Gets the value of the jdkVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJdkVersion() {
            return jdkVersion;
        }

        /**
         * Sets the value of the jdkVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJdkVersion(String value) {
            this.jdkVersion = value;
        }

        /**
         * Gets the value of the osVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOsVersion() {
            return osVersion;
        }

        /**
         * Sets the value of the osVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOsVersion(String value) {
            this.osVersion = value;
        }

        /**
         * Gets the value of the javaMemory property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJavaMemory() {
            return javaMemory;
        }

        /**
         * Sets the value of the javaMemory property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJavaMemory(String value) {
            this.javaMemory = value;
        }

        /**
         * Gets the value of the diskUsage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDiskUsage() {
            return diskUsage;
        }

        /**
         * Sets the value of the diskUsage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDiskUsage(String value) {
            this.diskUsage = value;
        }

        /**
         * Gets the value of the appServerVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAppServerVersion() {
            return appServerVersion;
        }

        /**
         * Sets the value of the appServerVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAppServerVersion(String value) {
            this.appServerVersion = value;
        }

        /**
         * Gets the value of the axis2Version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAxis2Version() {
            return axis2Version;
        }

        /**
         * Sets the value of the axis2Version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAxis2Version(String value) {
            this.axis2Version = value;
        }

    }

}
