////////////////////////////////////////////////
// CRC index creation file					 //
// $Id: QueryProcessor_index.sql,v 1.1 2007/05/23 19:24:55 rk903 Exp $			
// Check schema name before running this script			
////////////////////////////////////////////////

CREATE UNIQUE INDEX demodata.OBSERVATION_FACT_PK ON demodata.OBSERVATION_FACT
(ENCOUNTER_NUM,
PATIENT_NUM,
CONCEPT_CD,
PROVIDER_ID,
START_DATE,
MODIFIER_CD)
NOLOGGING ;


CREATE INDEX demodata.FACT_NOLOB ON demodata.OBSERVATION_FACT
(PATIENT_NUM, START_DATE, 
CONCEPT_CD, ENCOUNTER_NUM, NVAL_NUM, 
TVAL_CHAR, VALTYPE_CD, 
MODIFIER_CD, VALUEFLAG_CD, 
PROVIDER_ID, 
QUANTITY_NUM, 
UNITS_CD, 
END_DATE, 
LOCATION_CD, 
CONFIDENCE_NUM, 
UPDATE_DATE, 
DOWNLOAD_DATE, 
IMPORT_DATE, 
SOURCESYSTEM_CD, 
UPLOAD_ID)
NOLOGGING ;



CREATE INDEX demodata.FACT_CNPT_PAT_ENCT_IDX ON demodata.OBSERVATION_FACT
(CONCEPT_CD, PATIENT_NUM, ENCOUNTER_NUM)
NOLOGGING ;

CREATE INDEX demodata.FACT_PATCON_DATE_PRVD_IDX ON demodata.OBSERVATION_FACT
(PATIENT_NUM, CONCEPT_CD, START_DATE, END_DATE, ENCOUNTER_NUM, 
PROVIDER_ID, NVAL_NUM, VALTYPE_CD)
NOLOGGING ;

CREATE UNIQUE INDEX demodata.VISIT_DIM_PK ON demodata.VISIT_DIMENSION
(PATIENT_NUM, ENCOUNTER_NUM)
NOLOGGING ;


CREATE INDEX demodata.VISITDIM_EN_PN_LP_IO_SD_IDX ON demodata.VISIT_DIMENSION
(ENCOUNTER_NUM, PATIENT_NUM, LOCATION_PATH, INOUT_CD, START_DATE)
NOLOGGING ;



CREATE INDEX demodata.VISITDIM_STD_EDD_IDX ON demodata.VISIT_DIMENSION
(START_DATE, END_DATE)
NOLOGGING ;
