//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.17 at 02:57:57 PM EDT 
//


package edu.harvard.i2b2.ontology.datavo.vdo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for conceptType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="conceptType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="key_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="synonym_cd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="visualattributes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalnum" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="basecode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="metadataxml" type="{http://www.i2b2.org/xsd/cell/ont/1.1/}xml_valueType"/>
 *         &lt;element name="facttablecolumn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tablename" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="columnname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="columndatatype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="operator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dimcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tooltip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="protected_access" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ontology_protection" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="update_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="download_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="import_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="sourcesystem_cd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="valuetype_cd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modifier" type="{http://www.i2b2.org/xsd/cell/ont/1.1/}modifierType"/>
 *         &lt;element name="domain_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="on_parent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "conceptType", propOrder = {
    "level",
    "key",
    "keyName",
    "name",
    "synonymCd",
    "visualattributes",
    "totalnum",
    "basecode",
    "metadataxml",
    "facttablecolumn",
    "tablename",
    "columnname",
    "columndatatype",
    "operator",
    "dimcode",
    "comment",
    "tooltip",
    "protectedAccess",
    "ontologyProtection",
    "updateDate",
    "downloadDate",
    "importDate",
    "sourcesystemCd",
    "valuetypeCd",
    "modifier",
    "domainName",
    "onParent",
    "mAppliedPath"
})
public class ConceptType {

    protected int level;
    @XmlElement(required = true)
    protected String key;
    @XmlElement(name = "key_name", required = true)
    protected String keyName;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "synonym_cd", required = true)
    protected String synonymCd;
    @XmlElement(required = true)
    protected String visualattributes;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer totalnum;
    @XmlElement(required = true)
    protected String basecode;
    @XmlElement(required = true)
    protected XmlValueType metadataxml;
    @XmlElement(required = true)
    protected String facttablecolumn;
    @XmlElement(required = true)
    protected String tablename;
    @XmlElement(required = true)
    protected String columnname;
    @XmlElement(required = true)
    protected String columndatatype;
    @XmlElement(required = true)
    protected String operator;
    @XmlElement(required = true)
    protected String dimcode;
    @XmlElement(required = true)
    protected String comment;
    @XmlElement(required = true)
    protected String tooltip;
    @XmlElement(name = "protected_access", required = true)
    protected String protectedAccess;
    @XmlElement(name = "ontology_protection", required = true)
    protected String ontologyProtection;
    @XmlElement(name = "update_date", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updateDate;
    @XmlElement(name = "download_date", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar downloadDate;
    @XmlElement(name = "import_date", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar importDate;
    @XmlElement(name = "sourcesystem_cd", required = true)
    protected String sourcesystemCd;
    @XmlElement(name = "valuetype_cd", required = true)
    protected String valuetypeCd;
    @XmlElement(required = true)
    protected ModifierType modifier;
    @XmlElement(name = "domain_name", required = true)
    protected String domainName;
    @XmlElement(name = "on_parent", required = true)
    protected String onParent;

    @XmlElement(name = "m_applied_path", required = false)
    protected  String mAppliedPath;
    /**
     * Gets the value of the level property.
     * 
     */
    public int getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     */
    public void setLevel(int value) {
        this.level = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the keyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyName() {
        return keyName;
    }

    /**
     * Sets the value of the keyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyName(String value) {
        this.keyName = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the synonymCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSynonymCd() {
        return synonymCd;
    }

    /**
     * Sets the value of the synonymCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSynonymCd(String value) {
        this.synonymCd = value;
    }

    /**
     * Gets the value of the visualattributes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisualattributes() {
        return visualattributes;
    }

    /**
     * Sets the value of the visualattributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisualattributes(String value) {
        this.visualattributes = value;
    }

    /**
     * Gets the value of the totalnum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalnum() {
        return totalnum;
    }

    /**
     * Sets the value of the totalnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalnum(Integer value) {
        this.totalnum = value;
    }

    /**
     * Gets the value of the basecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBasecode() {
        return basecode;
    }

    /**
     * Sets the value of the basecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBasecode(String value) {
        this.basecode = value;
    }

    /**
     * Gets the value of the metadataxml property.
     * 
     * @return
     *     possible object is
     *     {@link XmlValueType }
     *     
     */
    public XmlValueType getMetadataxml() {
        return metadataxml;
    }

    /**
     * Sets the value of the metadataxml property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlValueType }
     *     
     */
    public void setMetadataxml(XmlValueType value) {
        this.metadataxml = value;
    }

    /**
     * Gets the value of the facttablecolumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacttablecolumn() {
        return facttablecolumn;
    }

    /**
     * Sets the value of the facttablecolumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacttablecolumn(String value) {
        this.facttablecolumn = value;
    }

    /**
     * Gets the value of the tablename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTablename() {
        return tablename;
    }

    /**
     * Sets the value of the tablename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTablename(String value) {
        this.tablename = value;
    }

    /**
     * Gets the value of the columnname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumnname() {
        return columnname;
    }

    /**
     * Sets the value of the columnname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumnname(String value) {
        this.columnname = value;
    }

    /**
     * Gets the value of the columndatatype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumndatatype() {
        return columndatatype;
    }

    /**
     * Sets the value of the columndatatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumndatatype(String value) {
        this.columndatatype = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperator(String value) {
        this.operator = value;
    }

    /**
     * Gets the value of the dimcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDimcode() {
        return dimcode;
    }

    /**
     * Sets the value of the dimcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDimcode(String value) {
        this.dimcode = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the tooltip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTooltip() {
        return tooltip;
    }

    /**
     * Sets the value of the tooltip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTooltip(String value) {
        this.tooltip = value;
    }

    /**
     * Gets the value of the protectedAccess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtectedAccess() {
        return protectedAccess;
    }

    /**
     * Sets the value of the protectedAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtectedAccess(String value) {
        this.protectedAccess = value;
    }

    /**
     * Gets the value of the ontologyProtection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOntologyProtection() {
        return ontologyProtection;
    }

    /**
     * Sets the value of the ontologyProtection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOntologyProtection(String value) {
        this.ontologyProtection = value;
    }

    /**
     * Gets the value of the updateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdateDate() {
        return updateDate;
    }

    /**
     * Sets the value of the updateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdateDate(XMLGregorianCalendar value) {
        this.updateDate = value;
    }

    /**
     * Gets the value of the downloadDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDownloadDate() {
        return downloadDate;
    }

    /**
     * Sets the value of the downloadDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDownloadDate(XMLGregorianCalendar value) {
        this.downloadDate = value;
    }

    /**
     * Gets the value of the importDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getImportDate() {
        return importDate;
    }

    /**
     * Sets the value of the importDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setImportDate(XMLGregorianCalendar value) {
        this.importDate = value;
    }

    /**
     * Gets the value of the sourcesystemCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcesystemCd() {
        return sourcesystemCd;
    }

    /**
     * Sets the value of the sourcesystemCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcesystemCd(String value) {
        this.sourcesystemCd = value;
    }

    /**
     * Gets the value of the valuetypeCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValuetypeCd() {
        return valuetypeCd;
    }

    /**
     * Sets the value of the valuetypeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValuetypeCd(String value) {
        this.valuetypeCd = value;
    }

    /**
     * Gets the value of the modifier property.
     * 
     * @return
     *     possible object is
     *     {@link ModifierType }
     *     
     */
    public ModifierType getModifier() {
        return modifier;
    }

    /**
     * Sets the value of the modifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModifierType }
     *     
     */
    public void setModifier(ModifierType value) {
        this.modifier = value;
    }

    /**
     * Gets the value of the domainName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomainName() {
        return domainName;
    }

    /**
     * Sets the value of the domainName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomainName(String value) {
        this.domainName = value;
    }

    /**
     * Gets the value of the onParent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnParent() {
        return onParent;
    }

    /**
     * Sets the value of the onParent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnParent(String value) {
        this.onParent = value;
    }

    public void setMAppliedPath(String value) { this.mAppliedPath = value; }

    public String getMAppliedPath() { return this.mAppliedPath; }
}
