
ALTER TABLE "TABLE_ACCESS" RENAME COLUMN "C_PROJECT" TO "C_PROTECTED_ACCESS"

UPDATE "TABLE_ACCESS"
SET "C_PROTECTED_ACCESS"='N'

ALTER TABLE "TABLE_ACCESS" MODIFY ( "C_PROTECTED_ACCESS" CHAR(1) )

ALTER TABLE "TABLE_ACCESS" DROP COLUMN "C_ROLE"
	
ALTER TABLE "TABLE_ACCESS" RENAME COLUMN "C_TABLENAME" TO "C_DIMTABLENAME"



	
	