//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.13 at 11:04:35 AM EDT 
//


package edu.harvard.i2b2.crc.datavo.setfinder.query;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for analysis_plugin_metadata_responseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="analysis_plugin_metadata_responseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}responseType">
 *       &lt;sequence>
 *         &lt;element name="analysis_plugin_metadata_type" type="{http://www.i2b2.org/xsd/cell/crc/psm/1.1/}analysis_plugin_metadata_typeType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "analysis_plugin_metadata_responseType", propOrder = {
    "analysisPluginMetadataType"
})
public class AnalysisPluginMetadataResponseType
    extends ResponseType
{

    @XmlElement(name = "analysis_plugin_metadata_type")
    protected List<AnalysisPluginMetadataTypeType> analysisPluginMetadataType;

    /**
     * Gets the value of the analysisPluginMetadataType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the analysisPluginMetadataType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnalysisPluginMetadataType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnalysisPluginMetadataTypeType }
     * 
     * 
     */
    public List<AnalysisPluginMetadataTypeType> getAnalysisPluginMetadataType() {
        if (analysisPluginMetadataType == null) {
            analysisPluginMetadataType = new ArrayList<AnalysisPluginMetadataTypeType>();
        }
        return this.analysisPluginMetadataType;
    }

}
